import type {
  AppSettingsTarget,
  SettingsPanel,
  SettingsScreen,
} from './CreepyAndroidSettings.types';

/** Mirrors SettingsNavigator.SCREENS so TS/MCP can enumerate global screens. */
export const SETTINGS_SCREENS: readonly SettingsScreen[] = [
  'settings',
  'settingsSearch',
  'appDetails',
  'wifi',
  'wifiIp',
  'bluetooth',
  'wireless',
  'location',
  'display',
  'sound',
  'notifications',
  'accessibility',
  'assistant',
  'usageAccess',
  'notificationListener',
  'overlay',
  'writeSettings',
  'batteryOptimization',
  'unknownSources',
  'security',
  'privacy',
  'vpn',
  'nfc',
  'language',
  'dateTime',
  'keyboard',
  'developerOptions',
  'apps',
  'allApps',
  'defaultApps',
  'home',
  'batterySaver',
  'batteryUsage',
  'dataUsage',
  'airplaneMode',
  'apn',
  'roaming',
  'doNotDisturb',
  'doNotDisturbPriority',
  'storage',
  'deviceInfo',
  'systemUpdate',
  'sync',
  'addAccount',
  'userDictionary',
  'hardwareKeyboard',
  'captioning',
  'cast',
  'print',
  'dream',
  'autoRotateSettings',
  'webView',
  'allNotifications',
];

export const APP_SETTINGS_TARGETS: readonly AppSettingsTarget[] = [
  'appDetails',
  'appNotifications',
  'notificationChannel',
  'notificationBubbles',
  'appOpenByDefault',
  'appLocale',
  'appUsage',
  'backgroundData',
  'exactAlarm',
  'fullScreenIntent',
];

/** Android Settings Panels (API 29+): Internet Connectivity, Wi-Fi, Volume, NFC. */
export const SETTINGS_PANELS: readonly SettingsPanel[] = [
  'internet',
  'wifi',
  'volume',
  'nfc',
];
